### ISSUE TITLE
Modifying for Other Games

### ISSUE THREAD

**Issue by Mactastic1-5** [psforever/GameLogger#8]
The program wants to attach to the PlanetSide process. I changed a line in the code so that it attaches to another game's process. It says needs DLL version 1.2, not 1.1, so I changed the DLL version to 1.1. I compile again and now when I click attach, it detaches soon after. What is the problem? Also, where is the source for the DLL?

**Comment by pschord** [comment]
Hey there. I designed GameLogger to be somewhat extensible for use in other games. What you are trying to do will not work though. This is because the DLL that communicates with the logger is specific to planetside. The code for this DLL is currently closed source as it has a lot of PS specific hacks and game offsets.

I am quite interested in making a release to the game hacking community with a DLL template and stripped down GameLogger. How else can I help on this issue?

**Comment by Mactastic1-5** [comment]
Alright, thank you. I suggest you should make a stripped down version of the DLL open source.
